# Generated by Django 4.0.6 on 2022-07-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_project_owner'),
        ('contributor', '0001_initial'),
        ('project_contribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectConstribution',
            new_name='ProjectContribution',
        ),
    ]
