# Generated by Django 4.0.6 on 2022-07-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_owner'),
        ('project_contribution', '0003_alter_projectcontribution_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='project.project'),
        ),
    ]
