# Generated by Django 4.0.6 on 2022-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
