# Generated by Django 4.0.6 on 2022-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0006_alter_mainuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='contact_no',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
