# Generated by Django 4.0.6 on 2022-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0007_mainuser_address_mainuser_contact_no_mainuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='contact_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
