# Generated by Django 4.0.6 on 2022-07-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.client')),
                ('service_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed'), ('Pensioner', 'Pensioner'), ('Family-pensioner', 'Family-pensioner'), ('Business', 'Business'), ('Farmer', 'Farmer'), ('Student', 'Student')], max_length=20)),
            ],
            bases=('client.client',),
        ),
    ]
